id = "graphql"
name = "GraphQL"
version = "0.0.3"
schema_version = 1
authors = ["Ivan Buryak <ivan.buryak@gmail.com>"]
description = "GraphQL extension for Zed"
repository = "https://github.com/11bit/zed-extension-graphql"

[language_servers.graphql]
name = "GraphQL Language Server"
language = "GraphQL"
languages = [
    "JavaScript",
    "JSX",
    "TypeScript",
    "TSX",
    "Vue.js",
    "GraphQL",
    "Astro",
    "Svelte",
]

[language_servers.graphql.language_ids]
"Astro" = "astro"
"JSX" = "javascriptreact"
"JavaScript" = "javascript"
"Svelte" = "svelte"
"TSX" = "typescriptreact"
"TypeScript" = "typescript"
"Vue.js" = "vuejs"
"GraphQL" = "graphql"

[grammars.graphql]
repository = "https://github.com/11bit/tree-sitter-graphql"
commit = "951bde9fb3145b5f676204231e35f8b21d21f7b3"
