id = "graphql"
name = "GraphQL"
version = "0.0.3"
schema_version = 1
authors = ["Ivan Buryak <ivan.buryak@gmail.com>"]
description = "GraphQL extension for Zed"
repository = "https://github.com/11bit/zed-extension-graphql"

[grammars.graphql]
repository = "https://github.com/11bit/tree-sitter-graphql"
commit = "951bde9fb3145b5f676204231e35f8b21d21f7b3"
