name = "GraphQL"
grammar = "graphql"
path_suffixes = ["graphql", "gql"]
line_comments = ["# "]
autoclose_before = "}])"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = true },
]
prettier_parser_name = "graphql"
